site_name: Kelsey McCallister's Portfolio
site_URL: # site URL
repo_URL: 
edit_URI: edit/main/docs

docs_dir: docs

nav:
  - Welcome: 'index.md'
  - Guide: 'MkDocs Guide.md'

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    -navigation.tabs
    -navigation.sections
    -toc.integrate
    -navigation.top
    -content.tabs.link
    -content.code.annotation
    -content.code.copy
    -content.action.net
  language: en

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.saneheaders
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - attr_list
  - sane_lists
